### ISSUE TITLE
Questions and doubts

### ISSUE THREAD

**Issue by Jostico96** [illixion/root-my-webos-tv#3]

**Comment by Jostico96** [comment]
I need a video tutorial. Since the script returns the IP to me, but it hasn't even arrived. I have not been able to install any additional applications

**Comment by illixion** [comment]
I'm not sure what you mean. Would you be able to attach a screenshot and/or describe the steps you've taken?

**Comment by Jostico96** [comment]
After step 5 it was stuck.

**Comment by illixion** [comment]
You can try this project if you're having trouble with mine, as it only requires a USB drive: https://github.com/throwaway96/dejavuln-autoroot

If you still intend on using my script, please post a screenshot of the main window. It's possible that your PC's LAN IP isn't being detected properly or you have a firewall that's blocking incoming connections.

**Comment by Jostico96** [comment]
I already have the IP
I skipped using putty but I'll try it later. I'll let you know if I was able to solve the problem.

**Comment by Jostico96** [comment]
finally I could finally root the tv after 2 months looking for alternatives.
I found the tutorial but I think you should explain it a little more.
I got lost in those details.
Let's see if it can last the applications now.
I have to say that I am not sure if it will last for a week or so.
perdon pero me toca con el traductor....
